name: weather_app
description: "A weather application which will provide users with real-time weather information, forecasts, and other weather-related data, which can help them make better decisions about their day-to-day activities"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^13.0.1

  # Connectivity
  dio: ^5.4.0

  # JSON 
  json_serializable: ^6.7.1

  # state-management
  riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
