name: weather_app
description: "A weather application which will provide users with real-time weather information, forecasts, and other weather-related data, which can help them make better decisions about their day-to-day activities"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^13.0.1

  # Connectivity
  dio: ^5.4.0
  retrofit: ^4.0.3

  # code-generation
  json_annotation: ^4.8.1

  # state-management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  envied: ^0.5.3
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: ^0.5.3
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
